export const FORGE_ROOT_MODULE = Symbol('FORGE_ROOT_MODULE');
export const FORGE_FIELD_MODULE_REF = Symbol('FORGE_FIELD_MODULE_REF');
export const FORGE_TOKEN_ROOT_MODULE = Symbol('FORGE_TOKEN_ROOT_MODULE');
